# Generated by Django 3.1 on 2020-08-21 10:34

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Page title')),
                ('description', models.TextField(blank=True, verbose_name='Page description')),
                ('slug', models.SlugField(editable=False, max_length=255)),
                ('content_markup', models.TextField(verbose_name='Content (Markdown)')),
                ('content_markup_html', models.TextField(editable=False)),
                ('background_image', models.ImageField(blank=True, upload_to=utils.get_upload_path, verbose_name='Page background')),
                ('is_shared', models.BooleanField(default=False, verbose_name='Shared?')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, size=None)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='categories.category')),
            ],
            options={
                'db_table': 'pages',
                'ordering': ['date_update'],
            },
        ),
    ]
